### ISSUE TITLE
[FEAT] iOS 3차 과제

### ISSUE THREAD

**Issue by Taehyeon-Kim** [29th-WE-SOPT-iOS-Part/KimTaeHyeon#15]
## 📌  Feature Issue

3차 과제는 TableView와 CollectionView의 적용입니다.
Youtube 앱의 메인 피드 UI를 구현합니다. (`실제 구독 뷰와 유사`)

## 📝  To-do

> ➡️ TableView 구성
- [x] 뷰 컨트롤러 TableView 생성 및 연결
- [x] FeedTableView Cell 생성 (Xib, Class) 
- [x] FeedTableView Cell 등록 및 호출

> ➡️ CollectionView 구성
- [x] TableView Cell 생성 (CollectionView 중첩)
- [x] TableView Cell 등록 및 호출
- [x] CollectionView Cell 생성 (Xib, Class)
- [x] CollectionView Cell 등록 및 호출

> ➡️ 상단바 구성
- [x] 상단바 AutoLayout 설정

> ➡️ 도전과제
- [x] 스크롤 시 상단바 숨김 처리
- [x] 카테고리 셀 구현 (CollectionView 사용) `동적 셀`

> ➡️ 리팩토링 (선택)
- [ ] 코드 정리
- [ ] 피드백 내용 반영 (피드백 있을 시)
- [ ] 텍스트 필드 키패드 설정
- [ ] 키보드에 따른 텍스트 필드 위치 조정
