### ISSUE TITLE
[🤖 REFACTOR] iOS 3차 과제 리팩토링

### ISSUE THREAD

**Issue by Taehyeon-Kim** [29th-WE-SOPT-iOS-Part/KimTaeHyeon#18]
## 📌  Feature Issue

진행했던 과제에 대해 리팩토링을 진행합니다.

## 📝  To-do

- [x] `UICollectionView Compositional Layout` 이용해서 리팩토링 ➡️ 중첩 구조를 최대한 벗어나기 위함
- [x] 데이터 모델 분리
- [x] 파일 및 폴더, 코드 정리
