### ISSUE TITLE
[⭐️ FEAT] iOS 4차 과제

### ISSUE THREAD

**Issue by Taehyeon-Kim** [29th-WE-SOPT-iOS-Part/KimTaeHyeon#20]
## 📌  Feature Issue

iOS 4차 과제는 `Networking`입니다.

## 📝  To-do

`기본`
- [x] Alamofire, Moya 의존성 설치하기
- [x] 홈 탭 화면에서 우측 상단 프로필 버튼 눌렀을 때 로그인 화면으로 화면 전환하기

`네트워크`
- [x] 네트워크 공통 상수 만들기 (ex. APIConstants)
- [x] 로그인, 회원가입 데이터 모델 만들기
- [x] 로그인, 회원가입 데이터 매니저 만들기
- [x] 로그인 서버 통신 후 alert 띄우기
- [x] 회원가입 서버 통신 후 alert 띄우기

`도전과제`
- [x] UserDefaults 이용해서 `name`값(`로그인 시 Response`) 저장하기

`리팩토링`
- 리팩토링 할 수 있는 부분은 같이 하면서 진행할 예정입니다.
