### ISSUE TITLE
[REFACTOR] iOS 1차 과제 리팩토링

### ISSUE THREAD

**Issue by Taehyeon-Kim** [29th-WE-SOPT-iOS-Part/KimTaeHyeon#7]
## 📌  Feature Issue

iOS 1차 과제를 리팩토링하려고 합니다.
생각보다 정리가 안 된 부분들이 있네요. 🤯

## 📝  To-do

- [x] 전체 코드 정리 (피드백 반영) 
- [x] Xib 파일 제거 (코드로 재구성하였습니다.)
- [x] 커스텀 텍스트 필드 적용(육회 스터디에서 만든 배민 스타일 텍필을 적용하려 합니다.✨)
- [x] 화면 전환 Closure 정리
